### ISSUE TITLE
about the data

### ISSUE THREAD

**Issue by Usernamezhx** [JakeRenn/pose_estimation#2]
hi JakeRenn
    im sorry to bother you . i am also followed by your https://github.com/HYPJUDY/human-pose-estimation-by-deep-learning . i want the data to train the model .thank you in advance!!! My email is zhanghx.jay@gmail.com

**Comment by JakeRenn** [comment]
@Usernamezhx Hi.

Actually, there are various public data set for pose estimation. 

RGB Image: MPII(http://human-pose.mpi-inf.mpg.de/)
Depth Image: ITOP(https://www.albert.cm/projects/viewpoint_3d_pose/)

**Comment by Usernamezhx** [comment]
thanks for your reply.
